Feat: Rollup weekdays
FutureTense/keymaster pull request #158
Opened 2021-05-08 21:59 UTC by tykeal

## Breaking change
None

## Proposed change
This makes the custom weekday listing a folded set. The reason being
that many times you just want to set the start and end datetimes and all
the extra options are just clutter.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information
None

2021-05-08 23:54 UTC, firstof9 requested changes

2021-05-08 23:54 UTC, firstof9 commented on custom_components/keymaster/lovelace.code
> +                  - type: 'custom:fold-entity-row'
Can you post an image with these changes in play?

2021-05-09 00:35 UTC, tykeal commented
@firstof9  here you go. I've been running with this for some time on my system.

![Selection_030](https://user-images.githubusercontent.com/1143598/117557012-b4e23680-b023-11eb-9c4f-580163cff6f9.png)

2021-05-09 03:04 UTC, firstof9 commented
LGTM, let me get a second opinion tho.

2021-05-09 03:05 UTC, firstof9 approved these changes

2021-05-09 03:37 UTC, raman325 commented
I like this, thanks for submitting!

2021-05-09 03:38 UTC, raman325 approved these changes

2021-05-09 03:38 UTC, merged