Fix all but one test
FutureTense/keymaster pull request #227
Opened 2021-09-09 22:19 UTC by raman325

## Breaking change

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

2021-09-09 22:20 UTC, raman325 commented
@firstof9 might need you to spend some time figuring out this last one, I'm at a loss

2021-09-09 22:31 UTC, firstof9 commented
Ooof looks like github's having trouble with openzwave...

2021-09-09 22:36 UTC, firstof9 commented
Try adding `sudo apt-get install libudev-dev` before the `pip install` in the work flow

2021-09-09 23:06 UTC, firstof9 commented
Well found the right `zwave_js_server` it's looking for, but the tests fail due to the code changes, we're kinda at the mercy of the pytest plugin, we'll have to wait for 2021.10.0b0 to drop before we can properly fix the tests right now.

2021-09-26 19:43 UTC, firstof9 commented
It's bailing on mqtt missing `Messages`

2021-09-28 00:10 UTC, firstof9 commented
Try changing line `29-36` of `tests/common.py`:

from:
```python
    with patch("homeassistant.components.mqtt.MQTT", return_value=AsyncMock()):
        mqtt_entry = MockConfigEntry(
            domain="mqtt",
            title="mqtt",
            data={CONF_BROKER: "http://127.0.0.1", CONF_PORT: 1883},
        )
        mqtt_entry.add_to_hass(hass)
        assert await hass.config_entries.async_setup(mqtt_entry.entry_id)
```

to:
```python
    mqtt_entry = MockConfigEntry(
        domain="mqtt", state=config_entries.ConfigEntryState.LOADED
    )
    mqtt_entry.add_to_hass(hass)
```

Let's see if that solves it.

2021-09-28 00:14 UTC, firstof9 requested changes

2021-09-28 00:14 UTC, firstof9 commented on tests/conftest.py
> +    yield
22-24 are duplicate lines of 281-283

2021-10-10 17:05 UTC, firstof9 commented
Looks like the tests are fixed by the magic of updated upstream dependencies 🎉

2021-10-10 17:05 UTC, merged