Remove zwave and ozw support
FutureTense/keymaster pull request #277
Opened 2022-04-16 06:59 UTC by raman325

## Breaking change

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

2022-04-22 20:36 UTC, firstof9 requested changes

2022-04-22 20:36 UTC, firstof9 commented on tests/test_config_flow.py
> -    state = hass.states.get("lock.smartcode_10_touchpad_electronic_deadbolt_locked")
Can we change this to load the zwavejs entities and verify the lock loads instead?

```python
    # Load ZwaveJS
    node = lock_kwikset_910
    state = hass.states.get(KWIKSET_910_LOCK_ENTITY)
```

2022-04-22 21:07 UTC, firstof9 commented
Tested the changes locally, and they do work.

2022-04-23 21:45 UTC, firstof9 approved these changes

2022-05-02 05:01 UTC, raman325 commented
@firstof9 thanks for adding the tests, clearly never got a chance to do it

2022-05-02 05:02 UTC, merged

2022-06-01 19:03 UTC, rcdailey commented
I saw this in the release notes and grew concerned:

- No reference from the release notes to documentation explaining how this is a breaking change or what manual actions I need to take (unless I missed it)
- Does this mean I can't use my Schlage Smart Deadbolt anymore (since it's zwave; provided via the zwavejs2mqtt plugin)?

2022-06-01 19:10 UTC, raman325 commented
> I saw this in the release notes and grew concerned:
> 
> * No reference from the release notes to documentation explaining how this is a breaking change or what manual actions I need to take (unless I missed it)
> * Does this mean I can't use my Schlage Smart Deadbolt anymore (since it's zwave; provided via the zwavejs2mqtt plugin)?

Locks using `zwave_js` will still work. Newer version of HA don't have the `zwave` or `ozw` integrations, so we got rid of the corresponding code. It's listed as a breaking change because it was worth highlighting, but it's not really a breaking change since `keymaster` is now pinned to versions of HA that no longer have those integrations anyway

2022-06-01 21:47 UTC, Monkey-Shiner commented
> > I saw this in the release notes and grew concerned:
> > 
> > * No reference from the release notes to documentation explaining how this is a breaking change or what manual actions I need to take (unless I missed it)
> > * Does this mean I can't use my Schlage Smart Deadbolt anymore (since it's zwave; provided via the zwavejs2mqtt plugin)?
> 
> Locks using `zwave_js` will still work. Newer version of HA don't have the `zwave` or `ozw` integrations, so we got rid of the corresponding code. It's listed as a breaking change because it was worth highlighting, but it's not really a breaking change since `keymaster` is now pinned to versions of HA that no longer have those integrations anyway

Thank you for the clarification!

2022-06-03 00:06 UTC, lishan89uc commented
> 

HAHAHAHA YOU scared the **** out of me ROFL!!!!! I thought my beautiful fe 599 will no longer work LOL!!!!