Fix options flow
FutureTense/keymaster pull request #8
Opened 2020-12-09 22:31 UTC by raman325

## Proposed change
Fix options flow

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

2020-12-09 22:38 UTC, firstof9 requested changes
Lets make sure to get https://github.com/FutureTense/keymaster/blob/816db55cd7d2f32d015a4d5ada8373049bfede06/custom_components/keymaster/config_flow.py#L114 fixed too.

2020-12-09 22:55 UTC, firstof9 approved these changes

2020-12-10 03:17 UTC, firstof9 requested changes
The async needs to be await'ed here:
https://github.com/FutureTense/keymaster/blob/816db55cd7d2f32d015a4d5ada8373049bfede06/custom_components/keymaster/config_flow.py#L114

2020-12-10 04:57 UTC, raman325 commented
🎉 for tests!

2020-12-10 09:05 UTC, merged